<?php $basePath = '..'; ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Grading criteria for Nora in Verona website" />
    <title>Grading - Nora in Verona</title>
    <link rel="stylesheet" href="../assets/css/styles.css" />
</head>

<body>
    <?php include __DIR__ . '/../components/navbar.php'; ?>

    <main class="container">
        <div class="page-header">
            <h2>Grading Criteria</h2>
        </div>

        <div class="page-single">
            <!-- Design -->
            <div class="component content-box-highlight">
                <h3 class="text-primary">1.Original JavaScript component</h3>
                <p>Not one generated by a program or retrieved from an archive.</p>
                <p>NO Libraries – (jQuery, Mootools, Scriptaculous, etc).</p>
                <p>This must be in addition to the form validation, above, and the DHTML element below.</p>
                <p>This must not be a silly addition that makes no sense, like a clock! This is sometimes tricky to
                    come up with something so chat with me early if you are struggling for an idea. Make sure to
                    document what you did on the grading/about page described below!

                </p>
            </div>

            <!-- Organization of Information -->
            <div class="component content-box-highlight">
                <h3 class="text-primary">2. DHTML component</h3>
                <p>
                    A DHTML component you created.</p>

                <p>The component selected should add some value to the page it's on; it should not be a silly addition
                    to the site.</p>

                <p>Something in the site should be animated, or style changed dynamically to fulfill this DHTML
                    requirement. Often times this will involve using the JS functions setTimeout(), or setInterval, to
                    animate something, or have something fade in or fade out based upon an event.</p>

                <p>Do NOT use a library for this element either.</p>
                <p>You may optinally combine the DHTML component with the JavaScript element from above. For example,
                    you could create an image gallery that allows a user to toggle through images (which satisfies the
                    requirements for #4 above) and when the images appear, they fade in (which satisfies the
                    requirements for the DHTML component).
                </p>
            </div>

            <!-- Quality and Quantity of Content -->
            <div class="component content-box-highlight">
                <h3 class="text-primary">3. Extras</h3>
                <p>
                    (see me what you did here, make it known where I can find these features to test)

                    Extra 1:

                    Extra 2:

                    Extra 3:

                    …

                    You WILL NOT receive credit for any of these components if they are not documented on your
                    about/grading page.
                </p>
            </div>

            <!-- Responsive Design -->
            <div class="component content-box-highlight">
                <h3 class="text-primary">4. Fixes from Project1 Critique</h3>
                <p>
                    1. Add a small indicator at the top to the side that allows the user to expand the navigational
                    element.
                    2. With your multi-column approach, you'll want to add additional media queries to adjust the total
                    internal columns of your content so it doesn't get too squished at mid-small sized screens.
                </p>
            </div>

            <!-- Accessibility and Usability -->
            <div class="component content-box-highlight">
                <h3 class="text-primary">4. Hard rules prof set</h3>
                <ul>
                    <li>NO Bootstrap templates!!!</li>

                    <li>Comment the CSS & HTML files</li>

                    <li>DO Not use the default link styles (recall a:link, a:visited etc)</li>

                    <li>PHP includes a must!!!</li>

                    <li>First page must be called index.php </li>

                    <li>Optimize all pictures for the web (you shouldn’t put a 5 megabyte image on the page. you should
                        resize/optimize/compress these with photoshop/photopea or some kind of software like we did in
                        web and mobile I. Including gigantic images will result in a deduction.)</li>

                    <li>FIX EVERYTHING I TOOK OFF FOR ON THE FIRST ONE!</li>
                </ul>
            </div>
        </div>

        <hr class="divider-thick" />

        <div class="quote-block">
            <p>
                <a href="../index.php" class="text-primary">Back to Home</a>
            </p>
        </div>
    </main>

    <?php include __DIR__ . '/../components/footer.php'; ?>

    <script src="../assets/js/script.js"></script>
</body>

</html>